spring.application.name=UniversityCourseOneToManyRelation

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=System
spring.datasource.password=Vaibhav
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Oracle Dialect
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect